### ISSUE TITLE
Feature: ClientAgent and Heartbeats

### ISSUE THREAD

**Issue by kestred** [Astron/Astron#261]
Clients are expected to send the CLIENT_HEARTBEAT message every so often.  The ClientAgent should accept this message, and disconnect clients who have not sent a heartbeat within a configurable amount of time (defaulting to some, semi-reasonable time like 5-30 seconds).'  A config value of 0 indicates that clients should not time out.

- [x] Add configuration message for heartbeat drop
- [x] Write a unittest for heartbeat drop (should config to 2-3 seconds and wait 4-5).
- [x] Accept and expect heartbeats in the ClientAgent

See `doc/protocol/10-client.md` for more information.

**Comment by bobbybee** [comment]
Pull request #328 should solve this issue (a.k.a.: bump)

**Comment by AlJaMa** [comment]
PR #328 Closes this issue.
