### ISSUE TITLE
Bring MongoDB into mainline Astron

### ISSUE THREAD

**Issue by CFSworks** [Astron/Astron#284]
The MongoDB backend has been behaving relatively stable in high-strain testing, with a few bugs:

- [x] MongoDB replication elections are not supported. (See #219.)
- [X] ~~The backend does not tolerate wrong-typed values. If an int is expected and a float is received, the backend will patently refuse to format a snapshot for the object.~~
- [X] Compilation is difficult. There are multiple (at least 3) versions of the MongoDB C++ driver, and not all of them are completely compatible with each other.
- [x] Multithreaded support is planned, but not implemented yet.

**Comment by AlJaMa** [comment]
It has been merged! :)

**Comment by kestred** [comment]
Yay!

**Comment by xHarv14** [comment]
An issue still remains, though it's fine that it's merged down:

- [ ] Astron will refuse to load data if we're expecting an integer but receive a float, or vice-versa. Fail-over support should be added to automatically convert the received value to the correct type, store the correct type in the database and then grab the object as per normal behaviour. This should also throw a warning to let the developer know that something went wrong, but it was handled gracefully. Perhaps a config option to only enable this in production?
