### ISSUE TITLE
Channel 12 not implemented?

### ISSUE THREAD

**Issue by loblao** [Astron/Astron#294]
So, I came across with an issue. I had to send an object update UD -> all AIs and for that I was sending the update to channel 12 (all State Servers), however I suspect it's not implemented yet, since the AIs didn't get the update (note that channel 10, all clients, does work).

I was digging into some code and found that client calls __subscribe_channel__ for **BCHAN_CLIENTS** (**Client.cpp, line 25**), however **StateServer.cpp** doesn't subscribe to **BCHAN_STATESERVERS**, only to their __control channel__, which cannot be used as DO update targets.

PS: To accomplish this I'm using the ugly "Hello UD, I'm an AI, my channel is X, send me your updates!"

**Comment by bobbybee** [comment]
This is addressed in the develop branch. Closing.
