### ISSUE TITLE
Config tests fail under Windows

### ISSUE THREAD

**Issue by xHarv14** [Astron/Astron#299]
test_config originally failed with the following:

```
======================================================================
FAIL: test_core_address_hosts (__main__.TestConfigCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config.py", line 173, in test_core_address_hosts
    self.assertEquals(self.checkConfig(config), 'Invalid')
AssertionError: 'Valid' != 'Invalid'
----------------------------------------------------------------------
Ran 10 tests in 8.579s
FAILED (failures=1)
```

however I resolved this by increasing the timeout for the config check from 2 to 4.

The bigger problem was when the following tests failed (test_config, test_config_clientagent and test_config_eventlogger respectively):

```
======================================================================
FAIL: test_core_address_hosts (__main__.TestConfigCore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config.py", line 181, in test_core_address_hosts
    self.assertEquals(self.checkConfig(config), 'Invalid')
AssertionError: 'Valid' != 'Invalid'
----------------------------------------------------------------------
Ran 10 tests in 18.882s
FAILED (failures=1)
```

```
======================================================================
FAIL: test_ca_bind_address (__main__.TestConfigClientAgent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config_clientagent.py", line 162, in test_ca_bind_address
    self.assertEquals(self.checkConfig(config), 'Invalid')
AssertionError: 'Valid' != 'Invalid'
----------------------------------------------------------------------
Ran 6 tests in 8.433s
FAILED (failures=1)
```

```
======================================================================
FAIL: test_eventlogger_bind_address (__main__.TestConfigEventLogger)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_config_eventlogger.py", line 31, in test_eventlogger_bind_address
    self.assertEquals(self.checkConfig(config), 'Invalid')
AssertionError: 'Valid' != 'Invalid'
----------------------------------------------------------------------
Ran 2 tests in 8.015s
FAILED (failures=1)
```

I did some poking around, and ran astrond manually using the configs that were used with the tests. It would seem that the process isn't actually exiting when astron_shutdown is called from within a non-MD component. It does seem that astron_shutdown is called (I see the "Exiting..." output) but the MD continues to run, which means the process is still running and the config test incorrectly returns "Valid" (since it checks if the process is still running).

**Comment by AlJaMa** [comment]
@xHarv14 Can you confirm that this is still the case?

**Comment by bobbybee** [comment]
@AlJaMa I thought we decided to screw Windows support?

**Comment by AlJaMa** [comment]
@bobbybee Though windows support is not a must have, if it is trivial to make changes to support it, we should.

**Comment by xHarv14** [comment]
@AlJaMa I can't confirm since I don't have a Windows system available right now, but there haven't been any changes (as far as I can see) to fix it. *cough* @kestred *cough* :dolphin:

**Comment by bobbybee** [comment]
@AlJaMa Fair enough.

**Comment by CFSworks** [comment]
If you ignore the year, this was a 2 day turnaround!

Closing this issue since [all core tests now pass on master on Windows](https://ci.appveyor.com/project/CFSworks/astron/build/%2316).
