### ISSUE TITLE
how do i build astron compatiable with mongodb

### ISSUE THREAD

**Issue by mgracer48** [Astron/Astron#310]
Do i just compile lastest version or do i need to do specific instructions
i want to use mongodb with my game

**Comment by Loudrob** [comment]
switch to the mongodb branch k

**Comment by kestred** [comment]
The mongodb branch is in development (though almost done! its more than functional to build stuff with).

Use the mongodb branch until https://github.com/Astron/Astron/pull/305 is merged into develop.
