### ISSUE TITLE
FindBoost

### ISSUE THREAD

**Issue by Loudrob** [Astron/Astron#312]
Is there a reason why FindBoost isn't included in the CMake?

**Comment by Wilee999** [comment]
ikr thanks a lot for making me spend months trying to find out why astron can never find boost until i finally figured out theres no findboost

**Comment by kestred** [comment]
FindBoost is a builtin module of CMake. See https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake.   If you are having problems finding boost, please set BOOST_ROOT or update your version of CMake.

**Comment by Wilee999** [comment]
BOOST_ROOT is defective and never worked. Why can't you guys just add a FindBoost?

**Comment by AlJaMa** [comment]
@Wilee999 as stated before, findBoost is an included cmake script. 


Secondly, open source projects' issue trackers are NOT the place to demand contributors to do anything.

**Comment by CFSworks** [comment]
[FindBoost is part of CMake](http://www.cmake.org/cmake/help/git-master/module/FindBoost.html).
