### ISSUE TITLE
putting in yaml database files into mongodb

### ISSUE THREAD

**Issue by mgracer48** [Astron/Astron#313]
No google searches are helping me with this. I need help. Im trying to put in yaml database files into mongodb so i dont lose everything . When i was using your astron before i used yaml but now i want to use mongodb if you guys can help that would be great.

**Comment by AlJaMa** [comment]
These tickets are considered spam. If you are looking for support please join us on irc

**Comment by bobbybee** [comment]
To clarify, we're in #Astron on chat.freenode.net

**Comment by kestred** [comment]
There is currently no built-in support for migrating databases.

It should be possible to cleanly perform a database migration by writing a script that calls `DBSERVER_OBJECT_GET_ALL` for each object in the source database, and using `DBSERVER_CREATE_OBJECT` to create the objects in the target database.

See Issue https://github.com/Astron/Astron/issues/314 for more details.

The Astron team is not planning to work on the feature, but pull requests are accepted.
