### ISSUE TITLE
building mongodb astron issue

### ISSUE THREAD

**Issue by mgracer48** [Astron/Astron#317]
Error	409	error C1083: Cannot open include file: 'mongo/client/dbclient.h': No such file or directory	C:\Users\michael\Desktop\Astron-feature-mongodb-backend\src\database\MongoDatabase.cpp	14	1	astrond
please help thank u

**Comment by mgracer48** [comment]
ah nvm i figured it out

**Comment by mgracer48** [comment]
well i tried making the source and linking cmake option to that but that didnt work and still same error this is so frustrating

**Comment by mgracer48** [comment]
My mongo  include  dir for cmake  is C:/Users/michael/Desktop/mongo-master/build/win32/64/mongo
what do i put for mongo libaries?

**Comment by mgracer48** [comment]
well i fixed it for real now :)

**Comment by AlJaMa** [comment]
@mgracer48 A friendly reminder: github issues are not the place to seek support. If you have something you believe is a bug, please report it with a description, methods to reproduce and the platform the error occurs on. 

If you continue to open tickets as you have been, I will be forced to ban you from the project.

**Comment by mgracer48** [comment]
Understood but thought it was a bug thought I would bring to your attention

**Comment by xHarv14** [comment]
As mentioned in previous posts, if you need help or support with compiling Astron, you are free to visit the #Astron channel over on Freenode. If you are unsure if something is a bug or not, the best place to ask would be in that channel. However we might not instantly be able to reply, so you may have to wait around.
