### ISSUE TITLE
Astron not compiling on windows visual studio 2013

### ISSUE THREAD

**Issue by mgracer48** [Astron/Astron#322]
Log is here 
http://pastebin.com/13qrDqMx

**Comment by AlJaMa** [comment]
Please provide more information. What platform you are on, and the EXACT steps you took starting from when you check the project out.


As mentioned in previous posts, if you need help or support with compiling Astron, you are free to visit the #Astron channel over on Freenode. If you are unsure if something is a bug or not, the best place to ask would be in that channel. However we might not instantly be able to reply, so you may have to wait around.

**Comment by mgracer48** [comment]
Ok im on windows, i checkouted it , compiled depependencies including mongodb and mongodb c++ driver pointed include to the built mongodb c++ and libaries to libmongo and linked in cmake the boost libaries and yaml and then i built debug version in visual studio 2013 and got this issue
