### ISSUE TITLE
Issue building mongodb-backend

### ISSUE THREAD

**Issue by HCreeperz** [Astron/Astron#323]
Hello, as i thought all was well in the "make" process, i encountered an issue about 'mutex'
The error is in the pastebin link below so i don't make much of a mess here.

http://pastebin.com/FjkfTqEQ

I am not sure whether or not it is my version of cmake, or c++, but any help would be greatly appreciated if it is or is not.

Sorry if this is irrelevant (because build status is unknown), or doesn't qualify as an issue, i'm new to doing issues

**Comment by AlJaMa** [comment]
@HCreeperz It could be many things. You have failed to provide 1) The os you are using. 2) The versions of boost and other libraries you are using. 3) The steps you took to get to this error.

**Comment by AlJaMa** [comment]
As mentioned in previous posts, if you need help or support with compiling Astron, you are free to visit the #Astron channel over on Freenode. If you are unsure if something is a bug or not, the best place to ask would be in that channel. However we might not instantly be able to reply, so you may have to wait around.
