### ISSUE TITLE
Astron crashes randomly on Windows when TLS is enabled

### ISSUE THREAD

**Issue by loblao** [Astron/Astron#327]
If I enable TLS to the CA

    tls:
        certificate: certs/dev/serverdev.crt
        key_file: certs/dev/serverdev.key
        cert_authority: certs/dev/clientdev.crt

Astron will randomly crash for no good reason when:
 * a client closes the connection (very frequent)
 * a state server connects to the MD (somewhat frequent, which is really strange since the MD doesn't relay on TLS afaik)
 * randomly (some what frequent)
 * right after the client connects (rare)

Extra info: 
 * The client does manage to connect.
 * Compiled with VS 2013, including all dependencies (yaml, OpenSSL and boost).

I'm currently testing this on Linux and trying to get a traceback on Windows.

**Comment by xHarv14** [comment]
What versions of Boost and OpenSSL are you using?

**Comment by loblao** [comment]
1.57.0 and 1.0.1g, respectively.

**Comment by loblao** [comment]
Unable to reproduce on Linux (Ubuntu 12.04, same Boost and OpenSSL versions).

**Comment by AlJaMa** [comment]
@loblao bump. I am unable to reproduce. If you aren't able to give a reproduction case in the next week this ticket will be closed.

**Comment by loblao** [comment]
Might just be my OS, I can't reproduce it anywhere else.

**Comment by loblao** [comment]
In fact this was caused the double-free, fixed in af3b151bc83d924c33bbbb2fac3d255fe51a34ae
