### ISSUE TITLE
CA not configured to use SSL

### ISSUE THREAD

**Issue by g0dfrey** [Astron/Astron#329]
So I have these files called libeay32.dll and ssleay32.dll and I'm having problems with mostly them.
One of the developers merged toon.dc and otp.dc into one file and didn't configure the ClientAgent,  so now it's literally impossible to start up the game for me.
I have Panda3D-190 installed, even a copy of panda inside the actual repository (I'll get to that later), and it's just weird, because we I didn't change any files at all and when astron and *.dlls got deleted I placed them back, they didn't anymore work.
I also tried testing the actual (astrond.exe) astron application if it works or not and even tried to revert the merge into one *.dc file, and it said in astron: "Failed to configure astrond.yml", which didn't even exist before and it worked perfectly. There is nothing wrong with my PPYTHON_PATH (it's set to use the panda inside the repository) and I get a message from AI and UD: "No module named panda.PandaModules", even though it's in there.
Help will be much appreciated, thanks.

**Comment by loblao** [comment]
This is not the right place to ask for help regarding Panda3D issues.

**Comment by AlJaMa** [comment]
@g0dfrey Github issues are not support.

**Comment by xHarv14** [comment]
Also, just to point it out: [Not Toontown](https://github.com/Astron/Astron/wiki/Not-Toontown)
