### ISSUE TITLE
Astron Error!

### ISSUE THREAD

**Issue by MidnightSynergyX** [Astron/Astron#330]
astron.exe is not a vaily in Win32 application
OS:Windows Xp
Please help!

**Comment by loblao** [comment]
Did you compile Astron yourself? I suspect you are trying to run a build compiled on Windows 7 or 8, which doesn't run on XP.

**Comment by MidnightSynergyX** [comment]
I did not compile Astron myself. can you please tell me how to compile Astron?

**Comment by loblao** [comment]
You can find it [here](https://github.com/Astron/Astron/blob/master/docs/building/windows-visualstudio.md).

**Comment by AlJaMa** [comment]
GitHub issues are not support
