### ISSUE TITLE
DatagramError compiling Linux Ubuntu 14.04.03

### ISSUE THREAD

**Issue by brownzilla** [Astron/Astron#342]
/root/repos/astron/src/clientagent/Client.cpp: In member function ‘virtual void Client::handle_datagram(DatagramHandle, DatagramIterator&)’:
/root/repos/astron/src/clientagent/Client.cpp:611:16: error: unused variable ‘old_parent’ [-Werror=unused-variable]
         doid_t old_parent = dgi.read_doid();
                ^
/root/repos/astron/src/clientagent/Client.cpp:612:16: error: unused variable ‘old_zone’ [-Werror=unused-variable]
         zone_t old_zone = dgi.read_zone();
                ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/astrond.dir/src/clientagent/Client.cpp.o] Error 1
make[1]: *** [CMakeFiles/astrond.dir/all] Error 2
make: *** [all] Error 2
root@ubuntuservergabe:~/repos/astron#

**Comment by AlJaMa** [comment]
Looks like your on a feature branch. Also looks like you have -WError on.... Which treats warnings as errors. 
try building in a confit other than release.
