### ISSUE TITLE
cmake can't find boost

### ISSUE THREAD

**Issue by TheCheapestPixels** [Astron/Astron#344]
I'm trying to build Astron on an Ubuntu 14.04, cmake version 2.8.12.2
libboost-system and libboost-filesystem are installed via apt, and are symlinked in the usual places:
$ ls -l /usr/lib/libboost_*
lrwxrwxrwx 1 root root 47 Apr 28 19:52 /usr/lib/libboost_filesystem-mt.a -> /usr/lib/x86_64-linux-gnu/libboost_filesystem.a
lrwxrwxrwx 1 root root 43 Apr 28 19:52 /usr/lib/libboost_system-mt.a -> /usr/lib/x86_64-linux-gnu/libboost_system.a
(Those linked files are also present, I did double-check.)

When invoking cmake:

$ cmake -DYAMLCPP_INCLUDE_DIR=dependencies/yaml-cpp-0.5.1/include/ \
>       -DYAMLCPP_LIBRARY=dependencies/yaml-cpp-0.5.1/build/libyaml-cpp.a \
>       -DSOCI_INCLUDE_DIR=dependencies/soci-3.2.3/ \
>       -DSOCI_LIBRARY=dependencies/soci-3.2.3/ \
>       -DCMAKE_BUILD_TYPE=Debug \
>       .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.6") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- GCC Version: 4.8

-- Found YamlCpp: /home/baribal/tmp/Astron/dependencies/yaml-cpp-0.5.1/include  
-- Found the following YamlCpp library:
  /home/baribal/tmp/Astron/dependencies/yaml-cpp-0.5.1/build/libyaml-cpp.a

-- Could NOT find Boost
-- Could NOT find Boost
CMake Error at CMakeLists.txt:134 (message):
  You need boost to build this, set the BOOST_ROOT or BOOSTROOT env
  variables, or pass them to cmake

-- Configuring incomplete, errors occurred!
See also "/home/baribal/tmp/Astron/CMakeFiles/CMakeOutput.log".

I tried passing the directory via 'export BOOSTROOT=/usr/lib/' and as -DBOOSTROOT=/usr/lib/ to cmake, which changed exactly nothing. How shall I proceed?

**Comment by mfwass** [comment]
How did you install boost?

**Comment by TheCheapestPixels** [comment]
Via apt, as stated above. Only boost-system and boost-filesystem should be required:

$ dpkg -l | grep -i 'boost.*system' | grep '\-dev'
ii  libboost-filesystem1.54-dev:amd64                     1.54.0-4ubuntu3.1                                   amd64        filesystem operations (portable paths, iteration over directories, etc) in C++
ii  libboost-system1.54-dev:amd64                         1.54.0-4ubuntu3.1                                   amd64        Operating system (e.g. diagnostics support) library

**Comment by ToontownLittleCat** [comment]
I think I've encountered this error before, have no idea how'd I fixed that.  But you could always just grab the source at http://boost.org, build the source, and install it.  Works for me.

**Comment by mfwass** [comment]
@TheCheapestPixels I agree with @ToontownLittleCat, try compiling them on your own and putting them in the ```dependencies``` folder.

**Comment by ToontownLittleCat** [comment]
@mfwass That might not be necessary,  usually, when invoking the install target on boost, it'll install the compiled build into the library and include directories.  CMake would find them automaticly find that way, removing the need of placing the build into ``dependencies`` directory.

**Comment by TheCheapestPixels** [comment]
Even more than in having a working Astron binary I am interested in Astron building for everybody without hacks and workarounds, so I'd rather like to see the build scripts fixed.

**Comment by mfwass** [comment]
@TheCheapestPixels Until the build script is fixed, I have provided a binary that can be used.
