### ISSUE TITLE
impl.h 'equals': identifier not found

### ISSUE THREAD

**Issue by xMakerx** [Astron/Astron#345]
I keep getting this error every time I attempt to build Astron. How do I resolve this?

**Comment by xHarv14** [comment]
This is an issue with YAML-CPP, not Astron.

**Comment by bobbybee** [comment]
@xHarv14 Sure, but what's the workaround then?

**Comment by xHarv14** [comment]
I believe it was fixed upstream a long time ago, but it was a simple missing include.
