### ISSUE TITLE
astron and saving strings

### ISSUE THREAD

**Issue by daviddave** [Astron/Astron#355]
When astron saves any strings it is turned into a list after it leaves my ud.
Thanks,
David

**Comment by loblao** [comment]
What he means is that YAML sometimes saves the file this way¹:

    id: 100000000
    class: Account
    fields:
      ACCOUNT_AV_SET: "[0, 0, 0, 0, 0, 0]"
      .......
      ACCOUNT_ID: "['d', 'e', 'v']"  <--------- incorrect
      ACCOUNT_ID: "\"dev\"" <--------- correct

dclass Account:

    dclass Account {
      string DcObjectType db;
      uint32 ACCOUNT_AV_SET[] required db;
      AvatarPendingDel ACCOUNT_AV_SET_DEL[] db;
      string CREATED db;
      string LAST_LOGIN db;
      string ACCOUNT_ID db;
      uint16 ACCESS_LEVEL db;
    };

I've had this issue in the past.

Trying to load that file causes Astron to die. This only happens with YAML.

¹: This was a long time ago, so I don't remember what exactly it generated, but it was a list.

**Comment by daviddave** [comment]
`	def enterCreateAccount(self):
		self.account = {'ACCOUNT_AV_SET': [0]*4,
						'ACCOUNT_AV_SET_DEL': [],
						'CREATED': time.ctime(),
						'LAST_LOGIN': time.ctime(),
						'ACCOUNT_ID': str(self.databaseId),
						'ADMIN_ACCESS': self.adminAccess}
		print str(self.databaseId)
		self.csm.air.dbInterface.createObject(
			self.csm.air.dbId,
			self.csm.air.dclassesByName['AccountUD'],
			self.account,
			__handleCreate)

	def __handleCreate(self, accountId):
		if self.state != 'CreateAccount':
			self.notify.warning('Received create account response outside of CreateAccount state.')
			return

		if not accountId:
			self.notify.warning('Database failed to construct an account object!')
			self.demand('Kill', 'Your account object could not be created in the game database.')
			return
		print 'accountCreated'
		self.csm.air.writeServerEvent('accountCreated', accountId)

		self.accountId = accountId
		self.demand('StoreAccountID')

	def enterStoreAccountID(self):
		print str(self.accountId)
		self.csm.accountDB.storeAccountID(self.databaseId, self.accountId, self.__handleStored)`
