### ISSUE TITLE
Astron on FreeBSD 10.2: undefined reference to symbol `pthread_create@@FBSD_1.0'

### ISSUE THREAD

**Issue by neelchauhan** [Astron/Astron#358]
I am trying to compile Astron on FreeBSD and when I compile, it fails at the linking step. The error I get is:

> [ 98%] Building CXX object CMakeFiles/astrond.dir/src/database/YAMLDatabase.cpp.o
[100%] Linking CXX executable astrond
/usr/bin/ld: undefined reference to symbol `pthread_create@@FBSD_1.0' (try adding -lthr)
//lib/libthr.so.3: could not read symbols: Bad value
CC: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

>Stop.
make[2]: stopped in /usr/home/neel/tmp/Astron
*** Error code 1

>Stop.
make[1]: stopped in /usr/home/neel/tmp/Astron
*** Error code 1

>Stop.
make: stopped in /usr/home/neel/tmp/Astron
neel@megan:~/tmp/Astron %

Is there a reason for this issue and how would I fix it?

**Comment by bobbybee** [comment]
(try adding -lthr)

**Comment by neelchauhan** [comment]
I figured how to fix this and have made a pull request for this.

**Comment by rajhlinux** [comment]
how did you fixed it?
