### ISSUE TITLE
I'm having trouble with astrond not being able to open a file.

### ISSUE THREAD

**Issue by ttchristopher** [Astron/Astron#362]
Is there a solution to this? http://prntscr.com/c2l72m

I've tried every possible way of trying to make this work. I've came to the Git hoping for solutions. Thanks in advance!

**Comment by DissonancePM** [comment]
Astron is looking for the configuration file in the current directory you are running astrond in. You'll have to create a [configuration file](https://github.com/Astron/Astron/blob/master/docs/config/astron.example.yml). If the config is elsewhere you may specify its location with a positional argument.
