### ISSUE TITLE
Owner view commit causes local avatar to delete itself on zone change

### ISSUE THREAD

**Issue by blueshark3** [Astron/Astron#383]
On the latest Astron commit, the local avatar deletes itself on a zone change (such as going into a street). This leads to crashes, naturally.

**Comment by CFSworks** [comment]
Astron's CA will disable any object that leaves visibility. This is now considered to be the case for owned objects that move out of interest as well. This sounds like an application-level bug and is therefore outside the scope of this project.

**Comment by loblao** [comment]
Make the avatar a session object to fix this.
