### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Ghost-0** [Astron/Astron#392]
Hi, i'm having an issue compiling Astron. Not exactly sure what i missed. I've done this many times in the past on Ubuntu so i thought it would work the same on Debian.

Error is in the paste:
https://pastebin.com/rZhACu46

Currently running on a 64bit install of Debian 9 Stretch.
The versions of things i've downloaded and compiled:
- boost-1_55_0
- yaml-cpp-0.5.1
- libmongocxx-3.1.3

If i missed something forgive me.

**Comment by CFSworks** [comment]
Debian Stretch ships with OpenSSL 1.1.0f; the 1.1 series made several API changes making it incompatible with Boost <1.62. So, Boost 1.55 will likely cause build problems for any SSL/TLS-capable application on Debian Stretch.

See also [Boost bug 12238](https://svn.boost.org/trac10/ticket/12238)
