### ISSUE TITLE
Failure to build Astron on Ubuntu 16.04

### ISSUE THREAD

**Issue by Kaiiku** [Astron/Astron#413]
I'm trying to build the latest version of Astron and I'm getting an error when using CMake saying that the LibUV libraries aren't found. I looked at the documentation and couldn't find anything related to it. I cloned and built LibUV in Astron/dependencies using the build instructions from their repository. All tests passed for LibUV and a libuv.so file was generated in libuv/out/cmake

This is the error I'm getting with CMake:
```
Could NOT find libuv (missing: LIBUV_INCLUDE_DIR LIBUV_LIBRARY
  LIBUV_LIBRARY_DIR)
```

**Comment by Psychotropos** [comment]
The CMake module for libuv doesn't seek for libuv within the dependencies directory, and the model of having dependencies within that directory is generally deprecated (pending removal).

Your best bet would be to either `make install` your build of libuv, or to simply install the libuv-dev package from Ubuntu's repository (see https://packages.ubuntu.com/search?keywords=libuv-dev)

**Comment by Kaiiku** [comment]
That worked, cheers!
