### ISSUE TITLE
MongoDB Implementation

### ISSUE THREAD

**Issue by RegDogg** [Astron/Astron#423]
Before I get started, i just want to say I'm a noob when it comes to the CMake compiling and this could probably be easily resolved.

Anyway, I would LOVE to add MongoDB Support in my Astron when its built into a executable file, How would I do this?

EDIT:I fixed my problem, just needed to download the mongo-cxx-driver

**Comment by RegDogg** [comment]
Sorry i just realised that i cannot start up Astron.exe after choosing database type: mongodb. It will crash after loading the Uberdogs and setting up the clientagent, Heres my config.yml. What did i do wrong?

`general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - otp.dc
        - toon.dc

messagedirector:
    bind: 127.0.0.1:7199
    threaded: false

uberdogs:
    - id: 4688
      class: CentralLogger
      anonymous: false

    - id: 4665
      class: ClientServicesManager
      anonymous: true

    - id: 4681
      class: ChatAgent
      anonymous: false

    - id: 4501
      class: FriendManager
      anonymous: false

    - id: 4686
      class: AvatarFriendsManager
      anonymous: false

    - id: 4687
      class: PlayerFriendsManager
      anonymous: false

    - id: 4666
      class: TTRFriendsManager
      anonymous: false

    - id: 4712
      class: TTSpeedchatRelay
      anonymous: false

    - id: 4683
      class: DistributedDeliveryManager
      anonymous: false

    - id: 4695
      class: TTCodeRedemptionMgr
      anonymous: false

    - id: 4477
      class: GlobalPartyManager
      anonymous: false

roles:
    - type: clientagent
      bind: 127.0.0.1:7198
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 4002

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: mongodb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: ../logs/events-%y%m%d_%H%M%S.log `

**Comment by mfwass** [comment]
```
- id: 4666
  class: TTRFriendsManager
  anonymous: false
```

[Please see this document.](https://github.com/Astron/Astron/wiki/Not-Toontown)

**Comment by RegDogg** [comment]
OFC this isn't Toontown, I've easily gotten Astron up and running with YAML Database. I juts need to find a way to get MongoDB working.

**Comment by RegDogg** [comment]
NVM I got TTR server working, I forgot to download MongoDB Compass
