### ISSUE TITLE
Update fails, update modal should be able to close/ignore it

### ISSUE THREAD

**Issue by juliancastroorozco** [Astron/Astron#441]
On android 8.1, update from 1.2.1 to 1.2.3 fails and shows error (see image below), every time I open Astron app, I get the update modal and can't close it making the app unusable 
![image](https://github.com/Astron/Astron/assets/36118800/56a83745-671e-457d-8ca9-d8d06c53ad71)

**Comment by maxrdz** [comment]
Are you talking of https://astron.cc? This open source project is not the software used in that application, the name might have confused you :P

**Comment by AlJaMa** [comment]
Hello! I'm sorry, but as mentioned in the previous comment it looks like this feedback is not intended for this project. I've closed the issue.
